version: '3'
services:
  #PHP Container
  app:
    image: devilbox/php-fpm:7.2-mods
    container_name: samp-app
    tty: true
    user: "devilbox:devilbox"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
    networks:
      - app-network

  #Nginx Container
  webserver:
    image: nginx:alpine
    container_name: samp-webserver
    tty: true
    working_dir: /var/www
    environment:
      APP_HOST: samp-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/app.template:/etc/nginx/app.template
      - ./.docker/nginx/conf.sh:/etc/nginx/conf.sh
    depends_on:
      - app
    entrypoint:
      - /etc/nginx/conf.sh
    command: nginx -g 'daemon off;'
    networks:
      - app-network

  #Node Container
  node:
    image: node:latest
    container_name: samp-node
    tty: true
    user: "node:node"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #MySQL Container
  database:
    image: mysql:5.7.25
    container_name: samp-database
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: samp
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #PhpMyAdmin Container
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: samp-phpmyadmin
    environment:
      PMA_HOST: samp-database
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - ./.docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./.docker/phpmyadmin/php/php-phpmyadmin.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
